site_name: ProperPath Documentation
site_url: https://uhd-urz.github.io/properpath/
repo_url: https://github.com/uhd-urz/properpath
repo_name: uhd-urz/properpath
nav:
  - Introduction: 'index.md'
  - Tutorial: 'tutorial.md'
  - API Reference:
      - 'apis/properpath.md'
      - 'apis/validators.md'
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: assets/path.svg
  favicon: assets/path.svg
  font:
    text: Lato
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.path
    - search.suggest
    - content.code.copy
    - navigation.sections

extra_css:
  - stylesheets/extra.css
extra:
  version:
    provider: mike
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/uhd-urz/properpath
      name: GitHub Repository
    - icon: fontawesome/solid/globe
      link: https://www.urz.uni-heidelberg.de/en
      name: Website
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/urz-rechenzentrum-der-universit%C3%A4t-heidelberg/about/
      name: LinkedIn
    - icon: fontawesome/brands/mastodon
      link: https://xn--baw-joa.social/@uniheidelbergIT
      name: Mastodon
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            members_order: source
            separate_signature: true
            show_signature_annotations: true
      options:
        allow_inspection: true
        docstring_style: "google"
copyright: ProperPath package is copyrighted under the MIT license.
